### ISSUE TITLE
job_hunting_using _web_scrapper

### ISSUE THREAD

**Issue by nancy-singh10** [anupammaurya6767/web_scrapper#10]
hey @anupammaurya6767 
Plz assign me this issue under hacktoberfest2023

**Comment by anupammaurya6767** [comment]
@nancy-singh10 go ahead

**Comment by Tejoooo** [comment]
hey @anupammaurya6767 Plz assign me this issue under hacktoberfest2023

**Comment by anupammaurya6767** [comment]
@Tejoooo Currently Nancy working on this
