### ISSUE TITLE
Creating a script for Devpost.

### ISSUE THREAD

**Issue by talha-ansarii** [anupammaurya6767/web_scrapper#2]
Scrapping upcoming hackathons and events.
@anupammaurya6767 I want to work on this issue under hacktober fest.

**Comment by anupammaurya6767** [comment]
@talha-ansarii go ahead

**Comment by tarun4632** [comment]
i want to work on this issue

**Comment by RumbleJack56** [comment]
I would sincerely request @anupammaurya6767  to grant me the permission to work on this noble issue.
