### ISSUE TITLE
scraping interships from linkedin 

### ISSUE THREAD

**Issue by tarun4632** [anupammaurya6767/web_scrapper#25]
mostly people are not aware of the latest internships and jobs and miss out a lot of internships in the end ... i am making a code that will regularly alert people about the internships and jobs in real time that are been updated on LinkedIn .. i would like to work on this issue @anupammaurya6767

**Comment by anupammaurya6767** [comment]
@tarun4632 go ahead

**Comment by josephlimtech** [comment]
Hi, I am from Proxycurl. I suggest that you use Jobs API to scrape for internships. For more information, you can check this link. https://nubela.co/proxycurl/docs#jobs-api-job-search-endpoint
