### ISSUE TITLE
Get a Recipe Idea to Get the Best Out of the Ingredients You Have.

### ISSUE THREAD

**Issue by talha-ansarii** [anupammaurya6767/web_scrapper#36]
I want to scrap this website "https://realfood.tesco.com/what-can-i-make-with.html " and write a script in which the ingredients names are entered by the user and the details of the best dish which can be made using these ingredients is returned.
@anupammaurya6767 please assign me this issue

**Comment by anupammaurya6767** [comment]
@talha-ansarii go ahead
