### ISSUE TITLE
Improve Code Readability and Efficiency

### ISSUE THREAD

**Issue by KavyaMalviya56** [anupammaurya6767/web_scrapper#48]
Description:
The current code lacks readability and can be optimized for better efficiency. We need to make the code more maintainable, and eliminate duplicate code to reduce complexity.

Tasks:

Refactor the code to remove duplicate XPath queries.
Add comments to explain the purpose of each section of the code.
Create a function to fetch the latest notice information to avoid redundant code.
Replace hard-coded URLs with variables.
Handle potential exceptions more gracefully with informative error messages.

@anupammaurya6767 assign me under hacktoberfest

**Comment by anupammaurya6767** [comment]
@KavyaMalviya56 go ahead
