### ISSUE TITLE
Refactor Code for Event Scraper

### ISSUE THREAD

**Issue by KavyaMalviya56** [anupammaurya6767/web_scrapper#50]
Description:
The current code for the Event Scraper could benefit from some improvements to make it more efficient, maintainable, and better organized.

Tasks:

Refactor the code to use a class, encapsulating the related functionality.
Improve code readability by adhering to PEP 8 style guidelines.
Make the MongoDB URI, database name, and endpoint URL configurable as class attributes.
Implement better exception handling for network requests.
Add comments to explain the purpose of each method and attribute.
Organize the code into distinct methods for easier maintenance.

@anupammaurya6767 assign this issue under hacktoberfest

**Comment by anupammaurya6767** [comment]
@KavyaMalviya56 go ahead
