### ISSUE TITLE
Refactor and Improve GeeksforGeeks Course Scraper

### ISSUE THREAD

**Issue by KavyaMalviya56** [anupammaurya6767/web_scrapper#54]
Description:
The existing code for scraping course data from GeeksforGeeks can benefit from refactoring and improvements for better organization, readability, and maintainability. This includes encapsulating functionality within a class and replacing hard-coded values with parameters.

Tasks:

Refactor the code into a class, encapsulating related functionality.
Improve code readability by following PEP 8 style guidelines.
Make the SQLite database connection and table creation more structured.
Implement better exception handling for database operations.
Replace hard-coded URLs with a parameter.
Organize the code into distinct methods for easier maintenance.
Add comments to explain the purpose of each method and attribute.

@anupammaurya6767 assign this under hacktoberfest

**Comment by anupammaurya6767** [comment]
@KavyaMalviya56 go ahead
