### ISSUE TITLE
Web Scrapper for anime website 

### ISSUE THREAD

**Issue by Shaurya10101** [anupammaurya6767/web_scrapper#9]
This project involves scraping information about anime ( title Rating genre ) on various anime websites like MAL , AniDB using Beautiful Soup . Please assign me this under Hacktoberfest 2023

**Comment by anupammaurya6767** [comment]
@Shaurya10101 go ahead

**Comment by anupammaurya6767** [comment]
@Shaurya10101 i guess you solved this issue?

**Comment by Shaurya10101** [comment]
Yeah .Thank you for the oppurtunity
